[build]
  base = "/"
  publish = "frontend/build/"
  command = "npm run build:plugins && npm run build:frontend"

[template.environment]
  NODE_ENV = "production"  

[[redirects]]
  from = "/*"
  to = "/"
  status = 200
